# Generated by Django 4.2.1 on 2023-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient/photos/'),
        ),
    ]
