# Generated by Django 4.2.1 on 2023-05-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0003_category_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
